Close modal when click android back button. Fix #356, Fix #392.
rsksmart/rwallet pull request #446
Opened 2020-08-31 02:44 UTC by AmazingBeerBelly

在打开rwallet进入密码验证的时候，如果点击安卓物理返回键，则退出app。在Dapp Browser的Modal显示情况下，点击安卓物理返回键，则关闭Modal。

![Kapture 2020-08-31 at 10 41 50](https://user-images.githubusercontent.com/25864116/91677907-b7c48780-eb76-11ea-8d53-8d2fd6ecc59c.gif)

2020-09-02 07:47 UTC, imstar15 commented on src/components/update/update.modal.js
> +        onRequestClose={() => {
这个函数应该放在标签外

2020-09-02 07:47 UTC, imstar15 commented on src/navigation/component.js
> +              onRequestClose={() => {
这个函数应该放在标签外

2020-09-02 07:54 UTC, imstar15 commented on src/navigation/component.js
> +              onRequestClose={() => {
这里的逻辑不正确，PasscodeModals在关闭的时候还需要调用passcodeFallback，
TouchSensorModal在关闭时还需要调用fingerprintFallback。

建议将onRequestClose的逻辑封装到PasscodeModals，TouchSensorModal各自的逻辑模块里。

2020-09-02 07:57 UTC, imstar15 requested changes
PasscodeModals在关闭的时候还需要调用passcodeFallback，
TouchSensorModal在关闭时还需要调用fingerprintFallback。

建议将onRequestClose的逻辑封装到PasscodeModals，TouchSensorModal各自的逻辑模块里。

2020-09-03 15:28 UTC, AmazingBeerBelly commented
onRequestClose方法只能加在Modal组件中，所以我这里做了判断 @imstar15

2020-09-04 07:09 UTC, imstar15 approved these changes

2020-09-04 07:11 UTC, imstar15 commented on src/navigation/component.js
> +    if (showPasscode && passcodeFallback) {
```suggestion
    if (showPasscode) {
      if (passcodeFallback)
        passcodeFallback();
      closePasscodeModal();
    }
```

2020-09-04 07:16 UTC, imstar15 approved these changes

2020-09-04 07:18 UTC, merged