Add wallet connect
rsksmart/rwallet pull request #457
Opened 2020-09-02 17:23 UTC by AmazingBeerBelly

代码还在整理优化中。

2020-09-02 23:50 UTC, chrisli30 requested changes
A few places with comments.

2020-09-02 23:50 UTC, chrisli30 commented on config.js
>      javascriptKey: '',
这个现在不用了，直接删了吧

2020-09-02 23:50 UTC, chrisli30 commented on src/common/apiHelper.js
> +};
All Parse cloud function calls are in ParseHelper. I don't think we need a new file for it.

2020-09-02 23:50 UTC, chrisli30 commented on src/pages/wallet/dashboard/list.js
> +        // }),
If not used any more let's delete the comment

2020-09-13 19:39 UTC, AmazingBeerBelly commented
1. Wallet is Connecting
![image](https://user-images.githubusercontent.com/25864116/93026547-4a662b80-f639-11ea-913a-38aa3b082a89.png)

2. 
![image](https://user-images.githubusercontent.com/25864116/93026311-b8a9ee80-f637-11ea-8920-abd10a9cb769.png)

![image](https://user-images.githubusercontent.com/25864116/93026324-ceb7af00-f637-11ea-83b0-b527e326823f.png)

![image](https://user-images.githubusercontent.com/25864116/93026333-decf8e80-f637-11ea-8acd-04abe18b2b1d.png)

![image](https://user-images.githubusercontent.com/25864116/93026348-f6a71280-f637-11ea-8537-a8d57946ae0e.png)

![image](https://user-images.githubusercontent.com/25864116/93026362-09b9e280-f638-11ea-8807-79f870c7ae6c.png)

![image](https://user-images.githubusercontent.com/25864116/93026738-c2812100-f63a-11ea-8526-f06409ef1e38.png)

![image](https://user-images.githubusercontent.com/25864116/93026798-45a27700-f63b-11ea-88d7-a88b47e03ade.png)

![image](https://user-images.githubusercontent.com/25864116/93026806-50f5a280-f63b-11ea-847a-ee806f5268c4.png)

![image](https://user-images.githubusercontent.com/25864116/93026893-d7aa7f80-f63b-11ea-983c-6511762bbf0b.png)

2020-09-13 20:36 UTC, AmazingBeerBelly commented
多语言现在只是做了英语的，其他的语言等确定之后再进行翻译。

2020-09-14 00:59 UTC, chrisli30 reviewed
没有大问题, @imstar15 看看？

2020-09-14 00:59 UTC, chrisli30 commented on src/common/apiHelper.js
> +      console.log('result: ', result.data);
确认没问题了就把log删了吧，清一下

2020-09-14 00:59 UTC, chrisli30 commented on src/common/common.js
> +  getCoinId(symbol, type) {
我怎么觉得这些funciton之前都写过？

2020-09-14 00:59 UTC, chrisli30 commented on src/common/translations/en.json
> +        "signApproved": "Sign Approved",
Approve Sign Message -> Approve Message Signing

Sign Approved -> Message Signing Approved

2020-09-14 07:10 UTC, chrisli30 approved these changes

2020-09-14 08:17 UTC, imstar15 commented on src/common/apiHelper.js
> +};
PARSE_SERVER_URL， 这个变量不能直接使用了， 现在应该使用Parse.serverURL，因为那个配置需要随发布环境变化。

2020-09-14 08:50 UTC, imstar15 commented on src/pages/wallet/dashboard/list.js
> -    if (coins.length === 1) {
这些处理不需要了吗？

2020-09-14 08:52 UTC, imstar15 commented on src/pages/wallet/transfer.js
> +        <TouchableOpacity onPress={() => {
onPress={approveRequest}

你看看这么写是不是也可以

2020-09-14 08:52 UTC, imstar15 commented on src/pages/wallet/transfer.js
> +          <Text>Approve</Text>
需要翻译文本

2020-09-14 12:52 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "selectAvailableWallet": "Por favor seleccione uma carteira que tenha pelo menos um ativo rsk mainnet",
```suggestion
        "selectAvailableWallet": "Por favor selecione uma carteira que tenha pelo menos um ativo na rede principal da rsk",
```

2020-09-14 12:55 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "isSigning": "Transação está assinando..",
```suggestion
        "isSigning": "A transação está sendo assinada..",
```

2020-09-14 12:56 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "signApproved": "Message Signing Approved",
```suggestion
        "signApproved": "Assinatura de mensagem aprovada",
```

2020-09-14 12:57 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "signApprovedDesc": "Sucesso!Sua mensagem foi assinada e deve aparecer na cabeça",
```suggestion
        "signApprovedDesc": "Sucesso!Sua mensagem foi assinada e deve aparecer no dapp",
```

2020-09-14 12:57 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "transactionApproved": "Transação Aprovada",
```suggestion
        "transactionApproved": "Transação aprovada",
```

2020-09-14 12:58 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "request": "Pedido",
```suggestion
        "request": "Solicitação",
```

2020-09-14 13:01 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "connectWallet": "%{dappName} solicita conectar sua carteira",
```suggestion
        "connectWallet": "%{dappName} pede para conectar sua carteira",
```

2020-09-14 13:02 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "agreeTo": "Clicar em Permitir, você concorda",
```suggestion
        "agreeTo": "Ao clicar em Permitir, você concorda em",
```

2020-09-14 13:05 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "waitingForOperations": "Esperando por operações",
```suggestion
        "waitingForOperations": "Aguardando por operações",
```

2020-09-14 13:06 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "minerFee": "Miner Fee",
```suggestion
        "minerFee": "Taxa de transação",
```

2020-09-14 13:07 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "gotIt": "GOT IT",
```suggestion
        "gotIt": "ENTENDI",
```

2020-09-14 13:07 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "leaveToDisconnect": "Deixar para desconectar?",
```suggestion
        "leaveToDisconnect": "Sair para desconectar?",
```

2020-09-14 13:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "leaveToDisconnectDesc": "Leaving Wallet Connect page will disconnect RWallet from the current connected Dapp.",
Sair da página Wallet Connect irá fazer com que a RWallet se desconecte do Dapp atualmente conectado.

2020-09-14 13:12 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "leaveToDisconnectConfirm": "Você tem certeza de desconectar?",
```suggestion
        "leaveToDisconnectConfirm": "Você tem certeza que deseja desconectar?",
```

2020-09-14 13:15 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "errorDesc": "Erro!Aconteceu um erro, por favor tente de novo mais tarde (pode haver muitas razões, como problemas de rede, rejeição do usuário, código de senha incorrecto, taxa de manejo ins
```suggestion
        "errorDesc": "Erro!Aconteceu um erro, por favor tente novamente mais tarde (pode haver muitas razões, como problemas de rede, rejeição do usuário, código de senha incorreto, taxa insuficiente, etc.)",
```

2020-09-14 13:15 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "tryAgain": "Tente de novo",
```suggestion
        "tryAgain": "Tente novamente",
```

2020-09-14 13:15 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "tryLater": "Tente mais tarde",
```suggestion
        "tryLater": "Tente novamente mais tarde",
```

2020-09-14 13:16 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveMessage": "Approve Message Signing",
```suggestion
        "approveMessage": "Aprovar assinatura de mensagem",
```

2020-09-14 13:18 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveMessageDesc": "Ao clicar em Confirmar, você concorda em assinar a mensagem originada de %{dappUrl}",
```suggestion
        "approveMessageDesc": "Ao clicar em Confirmar, você concorda em assinar a mensagem gerada por %{dappUrl}",
```

2020-09-14 13:20 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "successDesc": "Sucesso!Sua transação foi publicada para blockchain.Uma vez confirmado, ela deve aparecer na cobertura.",
```suggestion
        "successDesc": "Sucesso!Sua transação foi publicada na blockchain. Uma vez confirmada, ela deve aparecer no dapp.",
```

2020-09-14 13:20 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveTransaction": "Approve Transaction",
```suggestion
        "approveTransaction": "Aprovar transação",
```

2020-09-14 13:21 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveTransactionDesc": "Ao clicar em Confirmar, você concorda em assinar a transação originada de %{dappUrl}",
```suggestion
        "approveTransactionDesc": "Ao clicar em Confirmar, você concorda em assinar a transação gerada por %{dappUrl}",
```

2020-09-14 13:21 UTC, bitcoinuser requested changes
Changes on Portuguese Brazilian translation

2020-09-14 13:29 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "isConnecting": "A carteira está conectando...",
```suggestion
        "isConnecting": "Conectando carteira...",
```

2020-09-14 13:29 UTC, bitcoinuser requested changes
Minor change

2020-09-14 13:37 UTC, bitcoinuser requested changes
Minor changes

2020-09-14 13:50 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "agreeOne": "- Permitir obter o endereço atual da carteira",
```suggestion
        "agreeOne": "- Permitir fornecer o endereço atual da carteira",
```

2020-09-14 13:51 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "agreeTwo": "- Permitir o pedido de assinatura da carteira atual",
```suggestion
        "agreeTwo": "- Permitir que seja solicitado assinatura da carteira atual",
```

2020-09-14 13:52 UTC, bitcoinuser requested changes
Minor changes

2020-09-14 14:32 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "allowanceApproved": "Allowance Approved",
```suggestion
        "allowanceApproved": "Autorizado",
```

2020-09-14 14:33 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveAllowance": "Approve Allowance",
```suggestion
        "approveAllowance": "Autorizar",
```

2020-09-14 14:34 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveAllowanceDesc": "Ao clicar em Confirmar, você concorda em permitir %{dappUrl} transferir tokens em seu nome.",
```suggestion
        "approveAllowanceDesc": "Ao clicar em Confirmar, você concorda em autorizar %{dappUrl} transferir tokens em seu nome.",
```

2020-09-14 14:34 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "allowance": "Allowance",
```suggestion
        "allowance": "Autorizar",
```

2020-09-14 14:35 UTC, bitcoinuser requested changes
Minor changes

2020-09-15 04:10 UTC, chrisli30 approved these changes
这伙计真是翻译通啊

2020-09-15 17:02 UTC, bitcoinuser commented on src/common/translations/pt.json
> +        "approveAllowanceDesc": "Ao clicar em Confirmar, você concorda em permitir que %{dappUrl} transfira tokens em seu nome.",
```suggestion
        "approveAllowanceDesc": "Ao clicar em confirmar, você concorda em permitir que %{dappUrl} transfira tokens em seu nome.",
```

2020-09-15 17:03 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "agreeTo": "Ao clicar em Permitir, você concorda em",
```suggestion
        "agreeTo": "Ao clicar em permitir, você concorda em",
```

2020-09-15 17:03 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveAllowanceDesc": "Ao clicar em Confirmar, você concorda em autorizar %{dappUrl} transferir tokens em seu nome.",
```suggestion
        "approveAllowanceDesc": "Ao clicar em confirmar, você concorda em autorizar %{dappUrl} transferir tokens em seu nome.",
```

2020-09-15 17:04 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveMessageDesc": "Ao clicar em Confirmar, você concorda em assinar a mensagem gerada por %{dappUrl}",
```suggestion
        "approveMessageDesc": "Ao clicar em confirmar, você concorda em assinar a mensagem gerada por %{dappUrl}",
```

2020-09-15 17:04 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveTransactionDesc": "Ao clicar em Confirmar, você concorda em assinar a transação gerada por %{dappUrl}",
```suggestion
        "approveTransactionDesc": "Ao clicar em confirmar, você concorda em assinar a transação gerada por %{dappUrl}",
```

2020-09-15 17:05 UTC, bitcoinuser requested changes
Minor changes

2020-09-16 02:50 UTC, imstar15 commented on src/common/common.js
> +  getCoinId(symbol, type) {
ellipsisAddress专用做地址处理，判断0x开头省略，否则不省略。
里边去调用ellipsisString，就不用判断。

2020-09-16 03:55 UTC, imstar15 approved these changes
Nice!

2020-09-16 03:56 UTC, merged