Sort transaction by confirmed time and created time
rsksmart/rwallet pull request #467
Opened 2020-09-11 13:47 UTC by imstar15

2020-09-11 23:02 UTC, chrisli30 commented on src/redux/wallet/saga.js
> +  });
这个地方你看看，对于整个app来说，是不是没有createAt和confirmedAt的区别，显示的就是time，如果每个有显示的time的地方都需要做如下判断，那你在saga里拿到数据的时候就应该把这个time给处理了，外面所有的代码都不需要再次判断。
a.status === TxStatus.SUCCESS ? a.confirmedAt : a.createdAt

2020-09-12 00:54 UTC, imstar15 commented on src/redux/wallet/saga.js
> +  });
Fixed

2020-09-12 01:10 UTC, chrisli30 requested changes

2020-09-12 01:10 UTC, chrisli30 commented on src/common/parseDataUtil.js
> +    dateTime = dateTime ? moment(dateTime) : moment(0);
No you can't use moment(0). That's year 1970. Left it undefined here, and don't show in UI.

2020-09-12 05:25 UTC, chrisli30 approved these changes

2020-09-12 05:30 UTC, merged