Add confirm modal in dapp browser, fix ui issue, delete useless code. Fix #493
rsksmart/rwallet pull request #496
Opened 2020-09-25 16:46 UTC by AmazingBeerBelly

Transaction Modal:

<img width="404" alt="CleanShot 2020-09-26 at 00 44 10@2x" src="https://user-images.githubusercontent.com/25864116/94293781-677ff000-ff91-11ea-900d-b7933510c1c7.png">

Personal Sign Modal:

![image](https://user-images.githubusercontent.com/25864116/94293851-83839180-ff91-11ea-8631-5cb81abbf0b4.png)

Fix dapp warning modal issue:

![image](https://user-images.githubusercontent.com/25864116/94293933-9dbd6f80-ff91-11ea-9810-5cbfe7f53437.png)

2020-09-25 20:46 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "body": "%{description}Nota: Você será redirecionado para um Dapp de terceiros \"%{dappName}\". Por favor, analise cuidadosamente o Termo de Acordo do Usuário e a Política de Privacidade do Dap
```suggestion
      "body": "%{description}Nota: Você será redirecionado para um Dapp de terceiros \"%{dappName}\". Por favor, analise cuidadosamente o termo de acordo do usuário e a política de privacidade do Dapp. \"%{dappName}\" é responsável por todas as ações e usos no Dapp.\n\n"
```

2020-09-25 20:47 UTC, bitcoinuser requested changes
Minor changes on Portuguese Brazilian translation

2020-09-27 03:58 UTC, chrisli30 reviewed
Code looks good to me.

One minor change:
In the first screenshot, the "RBTC gas fee" should show only 6 decimal points; otherwise it's too long

2020-09-27 12:01 UTC, AmazingBeerBelly commented
<img width="404" alt="CleanShot 2020-09-26 at 00 44 10@2x" src="https://user-images.githubusercontent.com/25864116/94364469-ff015200-00fb-11eb-90cc-c45d0580f91d.png">

<img width="404" alt="CleanShot 2020-09-26 at 00 44 10@2x" src="https://user-images.githubusercontent.com/25864116/94364481-248e5b80-00fc-11eb-8f44-78c0ffc88d81.png">

2020-09-27 13:48 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "defaultDescription": "Você está sujeito ao Acordo de Utilizador e Política de Privacidade de Dapp de terceiros quando entra no Dapp de terceiros, que é diretamente e separadamente responsável
```suggestion
      "defaultDescription": "Ao utilizar Dapps de terceiros, você está sujeito ao termo de uso e a política de privacidade desses Dapps, que neste caso são de responsabilidade e fornecidos por \"%{dappName}\"."
```

2020-09-27 13:48 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "body": "%{description}\n\nNota: Você será redirecionado para um Dapp de terceiros \"%{dappName}\". Por favor, analise cuidadosamente o termo de acordo do usuário e a política de privacidade do
```suggestion
      "body": "%{description}\n\nNota: Você será redirecionado para um Dapp de terceiros \"%{dappName}\". Por favor, analise cuidadosamente o termo de uso e a política de privacidade do Dapp. \"%{dappName}\" é responsável por todas as ações e usos no Dapp.\n\n",
```

2020-09-27 13:50 UTC, bitcoinuser requested changes
Minor changes Portuguese Brazilian

2020-09-27 14:48 UTC, bitcoinuser requested changes
Minor change

2020-09-27 14:52 UTC, bitcoinuser requested changes
Minor change

2020-09-27 15:11 UTC, bitcoinuser requested changes
Minor change

2020-09-28 05:59 UTC, chrisli30 approved these changes

2020-09-29 06:34 UTC, imstar15 approved these changes

2020-09-29 06:49 UTC, merged