Create Raw Transaction in RWallet.
rsksmart/rwallet pull request #497
Opened 2020-09-25 17:11 UTC by AmazingBeerBelly

2020-09-25 17:16 UTC, AmazingBeerBelly commented on src/common/transaction/rbtccoin.js
> +    gas: 40000,
这里的gas计算，还有点问题。
普通的RBTC转账的gas是可以计算出来的，交易可以正常发送出去。但是其他的token的转账，即调用合约的transfer方法，计算出来的gas会小很多，然后把这笔交易发出去的时候，会因为gas太小而交易失败。计算出来的gas通常是23832，但是实际需要的gas是38852。

2020-09-27 01:49 UTC, chrisli30 commented on src/common/transaction/rbtccoin.js
> +    gas: 40000,
合约的调用，咱们这里后端应该是有常量值的，写死的

2020-09-27 01:49 UTC, chrisli30 commented on src/common/transaction/rbtccoin.js
> +  if (symbol === 'RBTC' || !contractAddress) {
This if should only check `symbol === 'RBTC' `

if symbol !== 'RBTC' && !contractAddress, the app should throw an error.

"Contract address for {symbol} is undefined."

2020-09-28 05:31 UTC, chrisli30 requested changes

2020-09-28 05:31 UTC, chrisli30 commented on src/common/transaction/rbtccoin.js
> +    throw new Error(`Contract address for ${symbol} is undefined.`);
这一句会不会crash app？外面有没有catch这个error并处理的逻辑？

我之前的意思是不行就弹出个错误框显示给用户，用户看到这个错误，发给我们，我们就知道是什么问题。

app应该是定义了一系列的错误信息了已经，如果之前没有定义过这个的话就加上一个错误class

2020-09-28 08:02 UTC, AmazingBeerBelly commented on src/common/transaction/rbtccoin.js
> +    throw new Error(`Contract address for ${symbol} is undefined.`);
不会crash app，外面都包有catch error，然后会弹窗提示错误。

2020-09-28 17:17 UTC, chrisli30 commented on src/common/transaction/rbtccoin.js
> +    throw new Error(`Contract address for ${symbol} is undefined.`);
Okay got it 👍

2020-09-28 17:17 UTC, chrisli30 approved these changes
Looking good!

2020-09-29 06:51 UTC, imstar15 requested changes

2020-09-29 06:51 UTC, imstar15 commented on src/pages/wallet/transfer.js
> +      } else if (symbol === 'RRTC') {
这块的分支逻辑可以封装到transaction对象的方法里，界面上调用就不需要看它的实现细节。

2020-09-29 23:19 UTC, chrisli30 approved these changes
The merge is good 👍

2020-09-30 07:29 UTC, imstar15 approved these changes

2020-09-30 07:32 UTC, merged