webview disable http request. Fix #501
rsksmart/rwallet pull request #503
Opened 2020-09-29 13:35 UTC by AmazingBeerBelly

When opening an "HTTP" website, rwallet will show an error notification (will add error notification translation after confirmed).

<img width="404" alt="CleanShot 2020-09-29 at 21 28 58@2x" src="https://user-images.githubusercontent.com/25864116/94564644-cc419000-029a-11eb-9e36-912929c32978.png">

Change the Dapp title.
In android, if the user opens "http://www.baidu.com", the title will be "http://www.baidu.com", but the webview actually opens "https://m.baidu.com/?from=844b&vit=fps". In this case, the webview will open normally, but the title is "http://www.baidu.com", it is not correct. So I use the domain name of the website as the title of this Dapp.

2020-09-29 23:15 UTC, chrisli30 approved these changes
Looks good. Let's update the text message.

2020-09-30 05:47 UTC, imstar15 requested changes

2020-09-30 05:47 UTC, imstar15 commented on ios/rwallet/Info.plist
>  		<key>NSAllowsArbitraryLoadsInWebContent</key>
关于这个配置直接删掉就可以了

2020-09-30 07:31 UTC, imstar15 approved these changes

2020-09-30 07:32 UTC, merged