Modify BTC min fee rate to 1sat/byte
rsksmart/rwallet pull request #526
Opened 2020-10-09 10:32 UTC by imstar15

![image](https://user-images.githubusercontent.com/16951509/95572663-ddd62500-0a5c-11eb-8eb4-60b548d11c80.png)

https://live.blockcypher.com/btc-testnet/tx/a89070393a563c7d222279de02b47d9828deb47af7be2708639f2ec16d01f3a7/

因为我们的transaction size是估算出来的（通过transactions列表），所以费用算出来并不是精确值。
比如说这个上面的例子，前端本地估算出来size是192 bytes，实际上是226 bytes。
前端向后端提交的是fees参数，是一个费用（rate*bytes），不是费率。

因此实际得到费率只能近似1sat/byte。

目前是这么实现。

2020-10-09 21:37 UTC, chrisli30 requested changes

2020-10-09 21:37 UTC, chrisli30 commented on src/pages/wallet/transfer.js
> +    this.txSize = null;
If existing code works well don't add unnecessary code. You changed the initial value of this.txSize to null, but didn't add any handling of the null value. If you don't have a clear reason to change it, then don't change it.

2020-10-10 08:20 UTC, imstar15 commented on src/pages/wallet/transfer.js
> +    this.txSize = null;
![image](https://user-images.githubusercontent.com/16951509/95650169-6794f980-0b14-11eb-82f3-2c284c172912.png)

当txSize等于null时，抛出异常。

2020-10-12 04:34 UTC, chrisli30 approved these changes

2020-10-12 09:32 UTC, merged