WalletConnect add network select
rsksmart/rwallet pull request #527
Opened 2020-10-09 11:05 UTC by AmazingBeerBelly

<img width="402" alt="CleanShot 2020-10-09 at 17 39 34@2x" src="https://user-images.githubusercontent.com/25864116/95575902-1fb59a00-0a62-11eb-8679-aceccbd50b80.png">

2020-10-09 11:33 UTC, imstar15 requested changes

2020-10-09 11:33 UTC, imstar15 commented on src/pages/wallet/wallet.connect/connecting.js
> +            titleStyle={styles.switchTitleStyle}
titleStyle，这个属性我并没有定义啊
如果你需要的话，可以往里加，叫textStyle吧

2020-10-09 12:03 UTC, AmazingBeerBelly commented on src/pages/wallet/wallet.connect/connecting.js
> +            titleStyle={styles.switchTitleStyle}
这是多余的代码，已经删掉了。

2020-10-09 13:09 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "selectTestnetAsset": "Selecione uma carteira que tenha pelo menos um ativo Testnet rsk",
```suggestion
        "selectTestnetAsset": "Selecione uma carteira que tenha pelo menos um ativo na rede de testes da rsk",
```

2020-10-09 13:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +          "body": "A testenet é uma cadeia alternativa de blocos RSK, a ser usada para testar."
```suggestion
          "body": "A rede de testes ou testnet é uma blockchain alternativa da RSK usada exclusivamente para realização de testes."
```

2020-10-09 13:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "mainnet": "Mainnet",
```suggestion
        "mainnet": "Rede prinicipal",
```

2020-10-09 13:12 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "testnet": "Testnet"
```suggestion
        "testnet": "Rede de testes"
```

2020-10-09 13:14 UTC, bitcoinuser requested changes
Changes Portuguese Brazilian

2020-10-09 21:58 UTC, chrisli30 requested changes

2020-10-12 04:35 UTC, chrisli30 approved these changes

2020-10-13 05:47 UTC, chrisli30 approved these changes

2020-10-14 02:17 UTC, chrisli30 commented
Need to test against Sovryn Testnet 
https://test.sovryn.app/

2020-10-14 05:51 UTC, imstar15 approved these changes

2020-10-15 23:05 UTC, chrisli30 approved these changes
Looking good. Only one comment left.

2020-10-15 23:05 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/modal/transaction.js
> +  const amount = value;
Add comment here why amount is value(and not Rsk3.utils.hexToNumber(value))

2020-10-16 17:53 UTC, chrisli30 approved these changes
There are two comments left in this PR. Please address those.

2020-10-16 17:53 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +    const net = isTestnet ? 'Testnet' : 'Mainnet';
net? should be called "network" ...

2020-10-16 17:53 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +const WALLET_CONNECTED = 'WalletConnected';
Address this issue?

2020-10-19 04:35 UTC, chrisli30 approved these changes

2020-10-19 10:22 UTC, imstar15 requested changes

2020-10-19 10:22 UTC, imstar15 commented on src/pages/wallet/wallet.connect/index.js
> +            await this.setState({ isTestnet: !isTestnet });
这个回调函数提出来
await  this.setState()，这样的写法不确定能不能行。
一般我们用this.setState({}, () => {})

2020-10-19 10:33 UTC, AmazingBeerBelly commented on src/pages/wallet/wallet.connect/index.js
> +            await this.setState({ isTestnet: !isTestnet });
await this.setState()可以的，跟this.setState({}, () => {})是一个作用

2020-10-20 03:03 UTC, chrisli30 approved these changes

2020-10-20 08:36 UTC, imstar15 approved these changes

2020-10-20 08:43 UTC, merged