add alert when wallet connect is disconnect. Fix #536
rsksmart/rwallet pull request #540
Opened 2020-10-12 14:29 UTC by AmazingBeerBelly

Add disconnect alert when WalletConnect disconnect.

<img width="408" alt="CleanShot 2020-10-12 at 22 14 18@2x" src="https://user-images.githubusercontent.com/25864116/95757880-4847c900-0cda-11eb-9ba9-39f095a88c4b.png">

2020-10-12 19:06 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "disconnectAlertTitle": "A conexão de carteira está desconectada",
```suggestion
        "disconnectAlertTitle": "Wallet Connect desconectada",
```

2020-10-12 19:10 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "disconnectAlertContent": "A conexão Wallet Connect com o Dapp \"%{dappName}\" está fechada.Isso pode ser devido ao fraco acesso à rede, interrupção do servidor Wallet Connect, ou rejeição un
```suggestion
        "disconnectAlertContent": "O Dapp \"%{dappName}\" foi desconectado da Wallet Connect. Pode ter ocorrido instabilidade no acesso à rede, interrupção do servidor da Wallet Connect, ou rejeição por parte do Dapp. Ao clicar no botão abaixo você será direcionado para a carteira.",
```

2020-10-12 19:12 UTC, bitcoinuser requested changes
Minor changes Portuguese Brazilian

2020-10-12 19:46 UTC, bgorlick commented
Some grammatical improvements to the message would be to use the below message:

The Wallet Connect connection to the Dapp "WalletConnect Example" is closed. This may be because of weak network access, Wallet Connect server interruptions, or a Dapp unilateral rejection (the Dapp itself rejected you directly for some reason). By clicking the button below you will be returned to the wallet dashboard.

2020-10-13 05:40 UTC, chrisli30 commented
> The Wallet Connect connection to the Dapp "WalletConnect Example" is closed. This may be because of weak network access, Wallet Connect server interruptions, or a Dapp unilateral rejection (the Dapp itself rejected you directly for some reason). By clicking the button below you will be returned to the wallet dashboard.

I agree. Let's remove the parens cause it looks informal. I also removed "Wallet Connect server interruptions". @AmazingBeerBelly please use below one.

The Wallet Connect connection to the Dapp "WalletConnect Example" is closed. This may be because of weak network access, or the Dapp rejected the wallet directly for some reason. 

By clicking the button below you will be returned to the wallet dashboard.

2020-10-13 15:38 UTC, bitcoinuser commented
> @bitcoinuser could you double check the translation for Portuguese? Thanks!

Done.

2020-10-13 17:14 UTC, AmazingBeerBelly commented
<img width="405" alt="CleanShot 2020-10-13 at 15 03 35@2x" src="https://user-images.githubusercontent.com/25864116/95893683-946a3a80-0dba-11eb-8e47-20db1e13698f.png">

2020-10-14 06:01 UTC, chrisli30 approved these changes
Looks good to me. Great work guys!

2020-10-14 06:11 UTC, imstar15 approved these changes

2020-10-14 06:12 UTC, merged