Alert user about checksum addreess
rsksmart/rwallet pull request #549
Opened 2020-10-16 13:09 UTC by imstar15

**lowercase**

![image](https://user-images.githubusercontent.com/16951509/96261381-f614e980-0ff2-11eb-8129-ba989dd7ff13.png)

**Copied from MetaMask**

![image](https://user-images.githubusercontent.com/16951509/96261460-117ff480-0ff3-11eb-963d-f976172400d8.png)

**Empty record**

**Testnet has no record, but Mainnet has.**
![image](https://user-images.githubusercontent.com/16951509/96262011-c4e8e900-0ff3-11eb-8aa2-da62a34e8eda.png)

**Testnet and Mainnet has no record.**
![image](https://user-images.githubusercontent.com/16951509/96261675-560b9000-0ff3-11eb-9ab0-00046fe83b5e.png)

2020-10-17 13:40 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "normal": "O endereço do destinatário inserido é um endereço RSK inválido. Certifique-se de que o endereço do destinatário é um endereço RSK válido e verifique-o no %{explorerName} antes de e
```suggestion
        "normal": "O endereço inserido é um endereço RSK inválido. Certifique-se de que o endereço do destinatário é um endereço RSK válido e verifique-o no %{explorerName} antes de enviar.",
```

2020-10-17 13:43 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "ethereum": "O endereço do destinatário inserido parece ser um endereço Ethereum. Este é um bug conhecido para valores copiados do Metamask. Certifique-se de que o endereço do destinatário é
```suggestion
        "ethereum": "O endereço inserido parece ser um endereço Ethereum. Este é um problema conhecido e ocorre quando se copia endereços da Metamask. Certifique-se de que o endereço do destinatário é um endereço RSK válido e verifique-o no %{explorerName} antes de enviar."
```

2020-10-17 13:44 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "question": "Por que você está vendo esta mensagem?",
```suggestion
      "question": "Por que estou vendo esta mensagem?",
```

2020-10-17 13:49 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "cancel": "Volte e entre novamente",
```suggestion
      "cancel": "Voltar e reinserir",
```

2020-10-17 13:50 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "confirm": "Ok, envie assim mesmo",
```suggestion
      "confirm": "Ok, enviar assim mesmo",
```

2020-10-17 13:50 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "asset": "De ativos",
```suggestion
      "asset": "Ativo",
```

2020-10-17 13:52 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "title": "Endereço de destinatário de registro vazio",
```suggestion
      "title": "Endereço sem registro",
```

2020-10-17 13:58 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "normal": "O endereço do destinatário inserido não tem registro em %{explorerName} e tem %{balance} %{otherSymbolName} na rede RSK ooo. Tem certeza de que deseja enviar %{amount} %{symbolName
```suggestion
        "normal": "O endereço inserido não tem registro na %{explorerName} e tem %{balance} %{otherSymbolName} na rede RSK. Tem certeza de que deseja enviar %{amount} %{symbolName} para o endereço RSK da %{type}?",
```

2020-10-17 14:03 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "both": "O endereço do destinatário inserido não tem registro em %{explorerName}. Tem certeza de que deseja enviar %{amount} %{symbolName} para o endereço em RSK %{type}?"
```suggestion
        "both": "O endereço inserido não tem registro na %{explorerName}. Tem certeza de que deseja enviar %{amount} %{symbolName} para o endereço RSK na %{type}?"
```

2020-10-17 14:06 UTC, bitcoinuser requested changes
Changes Portuguese Brazilian

2020-10-20 02:55 UTC, chrisli30 requested changes
Need to update the color of the checkbox to the same color of "The entered recipient address" paragraph

2020-10-20 08:24 UTC, chrisli30 approved these changes

2020-10-22 03:38 UTC, merged