Replace ethers to rsk3 (Dapp Browser, Wallet Connect). Fix #544
rsksmart/rwallet pull request #556
Opened 2020-10-18 19:42 UTC by AmazingBeerBelly

2020-10-19 03:14 UTC, imstar15 commented on src/pages/wallet/wallet.connect/index.js
>        gasLimit: params[0].gas || '0x927c0', // Set default gasLimit to 600000(hex: 0x927c0),
把这个常量定义到constants.js比较好，walletConnectGasLimit

2020-10-19 03:22 UTC, imstar15 requested changes

2020-10-19 03:22 UTC, imstar15 commented on src/pages/dapp/browser.js
> +      gasPrice: params[0].gasPrice || Rsk3.utils.BN(('1200000000')),
将预设值定义成常量

2020-10-19 04:04 UTC, chrisli30 commented on src/common/constants.js
> +};
@imstar15 我记得我们以前有这个default gas limit的设置了，在哪个常量里？

2020-10-19 04:04 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +    const rsk3 = new Rsk3(rskEndpoint);
其实这个变量叫provider也行。这样就不用改那些变量引用的代码

2020-10-19 05:06 UTC, imstar15 commented on src/common/constants.js
> +};
我查了一下源代码，没有相关的设置。
swap功能有个最低swap金额的限定，跟这个关系不大。

2020-10-19 10:16 UTC, imstar15 approved these changes

2020-10-20 02:50 UTC, chrisli30 approved these changes

2020-10-20 03:15 UTC, merged