Wallet Connect Add connect timeout alert
rsksmart/rwallet pull request #562
Opened 2020-10-20 09:47 UTC by AmazingBeerBelly

<img width="413" alt="CleanShot 2020-10-20 at 17 41 44@2x" src="https://user-images.githubusercontent.com/25864116/96569297-89a03000-12fb-11eb-840c-e5580d4d2959.png">

2020-10-21 10:57 UTC, imstar15 approved these changes

2020-10-21 12:20 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "timeoutTitle": "Wallet Connect timed out",
```suggestion
        "timeoutTitle": "Tempo expirado",
```

2020-10-21 12:22 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "timeoutBody": "RWallet não conseguia estabelecer uma conexão Wallet Connect com o Dapp dentro de um curto prazo.Por favor, tente de novo.",
```suggestion
        "timeoutBody": "A RWallet não conseguiu estabelecer uma conexão Wallet Connect com o Dapp dentro do prazo estabelecido. Por favor, tente novamente.",
```

2020-10-21 12:23 UTC, bitcoinuser requested changes
Changes Portuguese Brazilian

2020-10-21 22:04 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +      }, 20000);
这个用常量定义在constants文件里，以后改就直接改那里面的值，还有其他的timeout的值吗，可以都定义在一起

TIMEOUT_VALUE={
    "WALLET_CONNECT": 20, // 20 seconds
}

2020-10-23 03:00 UTC, chrisli30 approved these changes

2020-10-23 03:00 UTC, chrisli30 commented on src/common/constants.js
> +  WALLET_CONNECT: 20000, // 20000ms
注释改成 20 sec 吧 。清晰点

2020-10-23 03:23 UTC, merged