Pop up covert address modal to covert user-input address to checksum address.
rsksmart/rwallet pull request #563
Opened 2020-10-20 10:17 UTC by imstar15

**Convert  address**

![image](https://user-images.githubusercontent.com/16951509/96573265-76dc2a00-1300-11eb-9049-be6b334ab29a.png)

2020-10-20 13:08 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "title": "Endereço de carteira RSK inválido",
```suggestion
      "title": "Endereço RSK inválido",
```

2020-10-20 13:09 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "body": "O endereço da carteira inserido é um endereço RSK inválido. O RWallet tentará corrigi-lo automaticamente para o formato de endereço esperado. Você quer prosseguir?"
```suggestion
      "body": "O endereço RSK inserido é inválido. A RWallet tentará corrigi-lo automaticamente para o formato de endereço correto. Você deseja prosseguir?"
```

2020-10-20 13:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "body": "O endereço do contrato inserido é um endereço RSK inválido. O RWallet tentará corrigi-lo automaticamente para o formato de endereço esperado. Você quer prosseguir?"
```suggestion
      "body": "O endereço do contrato RSK inserido é inválido. A RWallet tentará corrigi-lo automaticamente para o formato de endereço correto. Você deseja prosseguir?"
```

2020-10-20 13:13 UTC, bitcoinuser requested changes
Changes Portuguese Brazilian

2020-10-21 22:01 UTC, chrisli30 approved these changes
The refactor looks good 👍

2020-10-22 03:59 UTC, merged