Add insufficient rbtc check in Wallet Connect
rsksmart/rwallet pull request #585
Opened 2020-10-29 16:09 UTC by AmazingBeerBelly

2020-10-29 18:36 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +          }
这个error的表现形式是怎样的？如果在我们的app里的话，错误信息应该是有个messageId，不然无法翻译到其他语言

2020-10-30 06:24 UTC, chrisli30 approved these changes

2020-10-30 06:29 UTC, imstar15 requested changes

2020-10-30 06:29 UTC, imstar15 commented on src/pages/wallet/wallet.connect/index.js
> +        'page.wallet.walletconnect.insufficientTitle',
这里的文本信息写在src/common/notification.controller.js里
```
export const errorNotifications = {
  [ERROR_CODE.ERC20_CONTRACT_NOT_FOUND]: {
    title: 'modal.contractNotFound.title',
    body: 'modal.contractNotFound.body',
  },
  [ERROR_CODE.ERR_REQUEST_TIMEOUT]: {
    title: 'modal.requestTimeout.title',
    body: 'modal.requestTimeout.body',
  },
....
}
```

调用处：
```
const notification = getErrorNotification(error.code) || getDefaultErrorNotification();
addNotification(notification);
```

可以参考下现有代码的实现

2020-10-30 06:31 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +        'page.wallet.walletconnect.insufficientTitle',
嗯，这里统一下吧

2020-11-02 08:51 UTC, imstar15 approved these changes

2020-11-02 08:52 UTC, merged