Minor changes Portuguese Brazilian
rsksmart/rwallet pull request #587
Opened 2020-10-29 23:18 UTC by bitcoinuser

2020-10-29 23:23 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "signApprovedDesc": "Sucesso!Sua mensagem foi assinada e deve aparecer no Dapp",
```suggestion
        "signApprovedDesc": "Sucesso!Sua mensagem foi assinada e deve aparecer no dapp",
```

2020-10-30 02:46 UTC, chrisli30 requested changes
Sorry, what's the reason to update RSK to Rsk?

2020-10-30 13:23 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "selectMainnetAsset": "Selecione uma carteira que tenha pelo menos um ativo na rede principal da Rsk",
```suggestion
        "selectMainnetAsset": "Selecione uma carteira que tenha pelo menos um ativo na rede principal da RSK",
```

2020-10-30 13:23 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "selectTestnetAsset": "Selecione uma carteira que tenha pelo menos um ativo na rede de testes da Rsk",
```suggestion
        "selectTestnetAsset": "Selecione uma carteira que tenha pelo menos um ativo na rede de testes da RSK",
```

2020-10-30 13:24 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +          "body": "A rede de testes ou testnet é uma blockchain alternativa da Rsk usada exclusivamente para realização de testes"
```suggestion
          "body": "A rede de testes ou testnet é uma blockchain alternativa da RSK usada exclusivamente para realização de testes"
```

2020-10-30 13:25 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "joinRSKCommunity": "Junte-se à comunidade Rsk",
```suggestion
        "joinRSKCommunity": "Junte-se à comunidade RSK",
```

2020-10-30 13:25 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "title": "Endereço Rsk inválido",
```suggestion
      "title": "Endereço RSK inválido",
```

2020-10-30 13:26 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "normal": "O endereço inserido é um endereço Rsk inválido. Certifique-se de que o endereço do destinatário é um endereço Rsk válido e verifique-o em %{explorerName} antes de enviar.",
```suggestion
        "normal": "O endereço inserido é um endereço RSK inválido. Certifique-se de que o endereço do destinatário é um endereço RSK válido e verifique-o em %{explorerName} antes de enviar.",
```

2020-10-30 13:26 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "normal": "O endereço inserido não tem registro em %{explorerName} e tem %{balance} %{otherSymbolName} na rede Rsk %{otherType}. Tem certeza de que deseja enviar %{amount} %{symbolName} para
```suggestion
        "normal": "O endereço inserido não tem registro em %{explorerName} e tem %{balance} %{otherSymbolName} na rede RSK %{otherType}. Tem certeza de que deseja enviar %{amount} %{symbolName} para o endereço RSK da %{type}?",
```

2020-10-30 13:26 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "title": "Endereço da carteira Rsk inválido",
```suggestion
      "title": "Endereço da carteira RSK inválido",
```

2020-10-30 13:27 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "body": "O endereço da carteira Rsk inserido é inválido. A RWallet tentará corrigi-lo automaticamente para o formato de endereço correto. Você deseja prosseguir?"
```suggestion
      "body": "O endereço da carteira RSK inserido é inválido. A RWallet tentará corrigi-lo automaticamente para o formato de endereço correto. Você deseja prosseguir?"
```

2020-10-30 13:27 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "title": "Endereço de contrato Rsk inválido",
```suggestion
      "title": "Endereço de contrato RSK inválido",
```

2020-10-30 13:27 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "body": "O endereço do contrato Rsk inserido é inválido. A RWallet tentará corrigi-lo automaticamente para o formato de endereço correto. Você deseja prosseguir?"
```suggestion
      "body": "O endereço do contrato RSK inserido é inválido. A RWallet tentará corrigi-lo automaticamente para o formato de endereço correto. Você deseja prosseguir?"
```

2020-10-30 13:28 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "both": "O endereço inserido não tem registro em %{explorerName}. Tem certeza de que deseja enviar %{amount} %{symbolName} para o endereço Rsk na %{type}?"
```suggestion
        "both": "O endereço inserido não tem registro em %{explorerName}. Tem certeza de que deseja enviar %{amount} %{symbolName} para o endereço RSK na %{type}?"
```

2020-10-30 13:28 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "ethereum": "O endereço inserido parece ser um endereço Ethereum. Este é um problema conhecido ao copiar endereços do MetaMask. Certifique-se de que o endereço do destinatário é um endereço R
```suggestion
        "ethereum": "O endereço inserido parece ser um endereço Ethereum. Este é um problema conhecido ao copiar endereços do MetaMask. Certifique-se de que o endereço do destinatário é um endereço RSK válido e verifique-o em %{explorerName} antes de enviar."
```

2020-10-30 13:36 UTC, bitcoinuser commented
> Sorry, what's the reason to update RSK to Rsk?

Ok, changed to RSK

2020-10-30 15:50 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
>          "signApprovedDesc": "Sucesso!Sua mensagem foi assinada e deve aparecer no dapp",
```suggestion
        "signApprovedDesc": "Sucesso! Sua mensagem foi assinada e deve aparecer no dapp",
```

2020-10-31 00:15 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "timeoutBody": "A RWallet não conseguiu estabelecer uma conexão WalletConnect com o Dapp dentro do prazo estabelecido. Por favor, tente novamente.",
```suggestion
        "timeoutBody": "A RWallet não conseguiu estabelecer uma conexão WalletConnect com o dapp dentro do prazo estabelecido. Por favor, tente novamente.",
```

2020-10-31 00:15 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "leaveToDisconnectDesc": "Sair da página WalletConnect irá fazer com que a RWallet se desconecte do Dapp atualmente conectado.",
```suggestion
        "leaveToDisconnectDesc": "Sair da página WalletConnect irá fazer com que a RWallet se desconecte do dapp atualmente conectado.",
```

2020-10-31 00:17 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
>          "errorDesc": "Erro!Aconteceu um erro, por favor tente novamente mais tarde (pode haver muitas razões, como problemas de rede, rejeição do usuário, código de senha incorreto, taxa insuficiente
```suggestion
        "errorDesc": "Erro! Aconteceu um erro, por favor tente novamente mais tarde (pode haver muitas razões, como problemas de rede, rejeição do usuário, código de senha incorreto, taxa insuficiente, etc.)",
```

2020-11-02 02:52 UTC, chrisli30 commented
@bitcoinuser Sorry, you need to merge all those commits into one and re-submit a PR. There are just too many commits in this PR.

2020-11-02 14:11 UTC, closed without merging