Fix sovryn out of gas issue. Fix #596
rsksmart/rwallet pull request #599
Opened 2020-11-05 05:18 UTC by AmazingBeerBelly

Sovryn's transaction failed because the gas is too low, so needs to calculate the current gas when gas is null.

2020-11-05 06:28 UTC, chrisli30 requested changes

2020-11-05 06:28 UTC, chrisli30 commented on src/pages/dapp/browser.js
> +    }
这些网络请求，如果超时，就走到不了下面的代码了，需要try catch吧？

2020-11-05 06:28 UTC, chrisli30 commented on src/pages/dapp/browser.js
> +    const toAddress = Rsk3.utils.toChecksumAddress(to, networkId);
如果to是undefined，传入这个函数会报错，在函数的一开始我们加个检查吧，然后to如果是undefined（很有可能是代码bug），怎么办，直接弹那个modal吗？

2020-11-05 06:28 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +    }
这些网络请求也是一样的吧，需要try catch？因为如果失败了你还可以继续往下走，用default的值

2020-11-05 10:28 UTC, AmazingBeerBelly commented on src/pages/dapp/browser.js
> +    const toAddress = Rsk3.utils.toChecksumAddress(to, networkId);
onMessage这个函数里面，有try catch，如果to是undefined的话，代码会报错，会弹出一个error modal。

2020-11-05 19:28 UTC, chrisli30 commented on src/pages/dapp/browser.js
> +    const toAddress = Rsk3.utils.toChecksumAddress(to, networkId);
好的，可以

2020-11-05 19:32 UTC, chrisli30 commented on src/pages/dapp/browser.js
> +        gas = TRANSACTION.DEFAULT_GAS_LIMIT;
Yeah this is actually better.

2020-11-05 19:32 UTC, chrisli30 commented on src/pages/dapp/browser.js
> +      value: value || TRANSACTION.DEFAULT_VALUE,
发送交易也有default value？如果value没有值不应该产生tx吧？。。

2020-11-05 19:32 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +      value: value || TRANSACTION.DEFAULT_VALUE,
这里也是，TRANSACTION.DEFAULT_VALUE是多少，能适用所有的交易吗

2020-11-06 02:36 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "errorTitle": "Fallou",
```suggestion
        "errorTitle": "Falhou",
```

2020-11-06 02:36 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "errorContent": "Aconteceu um erro desconhecido, por favor tente de novo mais tarde",
```suggestion
        "errorContent": "Ocorreu um erro desconhecido, por favor tente novamente mais tarde",
```

2020-11-06 02:37 UTC, bitcoinuser requested changes
Minor changes Brazilian Portuguese.

2020-11-06 03:31 UTC, chrisli30 approved these changes
Looks good!

2020-11-11 03:43 UTC, imstar15 requested changes

2020-11-11 03:43 UTC, imstar15 commented on src/pages/wallet/wallet.connect/modal/transaction.js
> +    value: PropTypes.oneOfType(PropTypes.number, PropTypes.string).isRequired,
PropTypes.oneOfType(array)

这个方法里的参数应该是array

2020-11-11 03:43 UTC, imstar15 commented on src/pages/wallet/wallet.connect/index.js
>        const notification = getErrorNotification(error.code, strings('page.wallet.walletconnect.tryLater'), error.message, this.rejectRequest);
const getErrorNotification = (errorCode, buttonText, messageParams, notificationCloseCallback)

这里为什么把error.message当作messageParams传进去呢？

2020-11-11 09:08 UTC, imstar15 approved these changes

2020-11-11 09:10 UTC, merged