Transaction modal display erc20 token info when call transfer, transferFrom, approve
rsksmart/rwallet pull request #608
Opened 2020-11-13 19:57 UTC by AmazingBeerBelly

有个问题是：调用erc20合约的方法的，我只找到了 https://live.sovryn.app/ 的approve交易，另外没有找到其他会调用到erc20的transfer或者transferFrom方法的dapp可以测试。

还有关于txData里面的value的问题，我现在是改成了，如果dapp那边不传value进来的话，我就默认设置成0，因为我发现sovryn和RNS这两款的dapp，里面有些交易的value是undefiend的。

<img width="419" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99114944-9ed35a80-262c-11eb-9a88-fe9b05a7f7ba.png">

2020-11-16 05:26 UTC, chrisli30 commented on src/common/apiHelper.js
> +      const result = await axios.post(url, { address: Rsk3.utils.toChecksumAddress(address) }, { headers, timeout: 5000 });
这个toChecksumAddress不是还不能转化正确的RSK地址？要转化成正确的需要做什么处理吗

2020-11-16 05:26 UTC, chrisli30 commented on src/pages/wallet/wallet.connect/index.js
> +      gasLimit: gas * 1.5,
gasLimit: gas * 1.5,
这一行的原因是什么，estimateGas的值会偏小吗？

2020-11-16 05:40 UTC, AmazingBeerBelly commented on src/pages/wallet/wallet.connect/index.js
> +      gasLimit: gas * 1.5,
是的，算出来的gas，比实际用到的gas要小，所以我这边保险一点，就乘了1.5倍。

2020-11-16 05:42 UTC, AmazingBeerBelly commented
<img width="405" alt="CleanShot 2020-11-16 at 13 34 21@2x" src="https://user-images.githubusercontent.com/25864116/99216782-81131a80-2811-11eb-95a0-10b516238d01.png">

2020-11-16 13:02 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "approveAllowanceDesc": "Ao clicar em Confirmar, você concorda em permitir %{dappUrl} paraexecutar chamadas de contrato inteligentes em seu nome.",
```suggestion
        "approveAllowanceDesc": "Ao clicar em confirmar, você concorda em permitir %{dappUrl} executar contratos inteligentes em seu nome.",
```

2020-11-16 13:02 UTC, bitcoinuser requested changes
Minor changes Portuguese Brazilian

2020-11-16 18:19 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "Spender": "Gastador",
```suggestion
        "Spender": "Usuário",
```

2020-11-16 18:19 UTC, bitcoinuser requested changes
Minor change Portuguese Brazilian

2020-11-17 06:43 UTC, chrisli30 requested changes

2020-11-17 06:43 UTC, chrisli30 commented on src/common/common.js
> +  formatInputData(inputData, symbol) {
这个是为了format contract的API address吧？叫formatContractABIInputData吧

2020-11-17 06:43 UTC, chrisli30 commented on src/common/common.js
> +        result[key] = this.ellipsisAddress(value);
星佑刚改的PR，to address是不能省略的，这里合约里的地址也不能省略，而且这个地址显示的时候还要加explorer的link

2020-11-17 09:57 UTC, chrisli30 approved these changes

2020-11-17 09:59 UTC, merged