Build BTC transaction locally
rsksmart/rwallet pull request #609
Opened 2020-11-16 14:00 UTC by imstar15

2020-11-17 08:14 UTC, chrisli30 requested changes

2020-11-17 08:14 UTC, chrisli30 commented on src/common/transaction/btccoin.js
> +  const { tx: { inputs } } = rawTransaction;
不能传rawTransaction进来，只能传inputs

2020-11-17 08:14 UTC, chrisli30 commented on src/common/transaction/btccoin.js
> +  }
对，output这里构造没问题

2020-11-17 23:42 UTC, chrisli30 requested changes

2020-11-17 23:42 UTC, chrisli30 commented on src/common/transaction/btccoin.js
> +  _.some(transactions, (transaction) => {
这里并不是_.some的真正用途，根据说明_.some是为了返回一个bool，这里你没有const isTrue = _.some()，需要的其实就是_.each，如果要skip一个iteration，就直接return, for example

```
 if (transaction.tx_output_n === -1) {
      return; // skip current iteration.
}
```

2020-11-17 23:42 UTC, chrisli30 commented on src/common/transaction/btccoin.js
>  export const getSignedTransactionHex = ({
这个函数的名称跟他的实际实现不符，这个函数其实做了两件事情
1. build a transaction
2. sign a traction

build的时候不需要传入 privateKey，
sign的时候只需要build好的inputs array

我建议把他们分开，
const inputs = await buildTransaction(addressInfo, toAddress, amount, netType, fees ); // addressInfo里都有fromAddress，fromAddress不需要再传入一遍

signTransaction(inputs)

2020-11-18 01:45 UTC, imstar15 commented on src/common/transaction/btccoin.js
> +  _.some(transactions, (transaction) => {
_.some的功能是在循环中，如果遇到迭代函数的返回值是true，则退出循环。

2020-11-18 06:22 UTC, chrisli30 approved these changes

2020-11-18 06:28 UTC, merged