Fix sovryn cannot connect wallet issue.
rsksmart/rwallet pull request #612
Opened 2020-11-18 16:17 UTC by AmazingBeerBelly

![1411605716211_ pic](https://user-images.githubusercontent.com/25864116/99556556-a1eb9380-29fc-11eb-96a4-a43fc3ff7b1f.jpg)

2020-11-18 21:15 UTC, chrisli30 approved these changes

2020-11-19 01:46 UTC, imstar15 requested changes

2020-11-19 01:46 UTC, imstar15 commented on src/pages/dapp/browser.js
> +                if (method === 'net_version') {
if...else分支大于3个，需改写成switch...case

2020-11-19 02:38 UTC, imstar15 approved these changes

2020-11-19 02:38 UTC, merged