Set default contract method in Transaction Modal
rsksmart/rwallet pull request #616
Opened 2020-11-19 08:40 UTC by AmazingBeerBelly

Sovryn:

<img width="419" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99641693-94c6b700-2a85-11eb-8931-eec74c1f3ba9.jpg">

<img width="419" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99641638-8082ba00-2a85-11eb-8626-27a8f3a14d4f.jpg">

RSK Swap:

<img width="419" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99641802-b7f16680-2a85-11eb-82cc-d485d2b8c5c2.jpg">

Money on Chain:

<img width="419" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99641872-cb043680-2a85-11eb-9521-ba8760af9441.jpg">

2020-11-19 09:10 UTC, imstar15 requested changes

2020-11-19 09:10 UTC, imstar15 commented on src/pages/wallet/wallet.connect/modal/allowance.js
> +              <Text style={styles.lineValue}>{`${Number(fee).toFixed(6)} RBTC`}</Text>
这个小数点，去config里定义的

2020-11-19 09:10 UTC, imstar15 commented on src/common/common.js
> +    return `0x${this.ellipsisString(completionAddress.substr(2, length), showLength)}`;
这里为啥不用之前写好的ellipsisAddress

2020-11-19 09:12 UTC, AmazingBeerBelly commented on src/common/common.js
> +    return `0x${this.ellipsisString(completionAddress.substr(2, length), showLength)}`;
这个就是之前写好的ellipsisAddress

2020-11-19 09:15 UTC, imstar15 commented on src/common/common.js
> +    return `0x${this.ellipsisString(completionAddress.substr(2, length), showLength)}`;
OK

2020-11-19 09:24 UTC, imstar15 approved these changes

2020-11-20 01:47 UTC, chrisli30 commented
> Sovryn:
> 
> <img alt="CleanShot 2020-11-14 at 03 49 34@2x" width="419" src="https://user-images.githubusercontent.com/25864116/99641693-94c6b700-2a85-11eb-8931-eec74c1f3ba9.jpg">
> 
> <img alt="CleanShot 2020-11-14 at 03 49 34@2x" width="419" src="https://user-images.githubusercontent.com/25864116/99641638-8082ba00-2a85-11eb-8626-27a8f3a14d4f.jpg">
> 
> RSK Swap:
> 
> <img alt="CleanShot 2020-11-14 at 03 49 34@2x" width="419" src="https://user-images.githubusercontent.com/25864116/99641802-b7f16680-2a85-11eb-82cc-d485d2b8c5c2.jpg">
> 
> Money on Chain:
> 
> <img alt="CleanShot 2020-11-14 at 03 49 34@2x" width="419" src="https://user-images.githubusercontent.com/25864116/99641872-cb043680-2a85-11eb-9521-ba8760af9441.jpg">

三种逻辑modal很乱，标题只分两种，是普通的转账就叫Approve Transaction，是智能合约调用，就叫Approve Smart Contract Call

在Approve Smart Contract Call 里，
不需要写type，如果你知道调用的method是什么，就写Method: Tranfer, TransferFrom, Approve （首字母全部答谢），不知道就不写，不要type field
所有已经解析出来的modal，不需要写data，现在解析的是Tranfer, TransferFrom, Approve，之后会添加，所以要有一个域能标志是否解析

2020-11-23 06:53 UTC, AmazingBeerBelly commented
Smart Contract Call (ERC20 Transfer)
<img width="300" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99935296-5a1d9100-2d9b-11eb-9583-9377ca9f963b.jpg">

Smart Contract Call (Approve)
<img width="300" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99935363-7e796d80-2d9b-11eb-9aab-aea3adecb79d.jpg">

Unparsed Smart Contract Call
<img width="300" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99935439-a8329480-2d9b-11eb-95e5-04ab6be4d757.jpg">

2020-11-23 07:07 UTC, imstar15 requested changes

2020-11-23 07:07 UTC, imstar15 commented on src/common/common.js
> +      const checksumAddress = Rsk3.utils.toChecksumAddress(address);
这句话，还是写成带chainId的。然后在fix_checksum的PR里再改它

2020-11-23 07:19 UTC, chrisli30 approved these changes

2020-11-23 07:20 UTC, chrisli30 commented on src/common/common.js
> +      const checksumAddress = Rsk3.utils.toChecksumAddress(address);
都行。如果这里写了，那个PR记得改

2020-11-23 08:06 UTC, AmazingBeerBelly commented
Smart Contract Call (ERC20 Transfer)
<img width="300" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99939745-c1404300-2da5-11eb-9288-6d9d70fdacaa.jpg">

Smart Contract Call (Approve)
<img width="300" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99939728-b2f22700-2da5-11eb-93d1-b1e8b9b63c5f.jpg">

Unparsed Smart Contract Call
<img width="300" alt="CleanShot 2020-11-14 at 03 49 34@2x" src="https://user-images.githubusercontent.com/25864116/99939774-cef5c880-2da5-11eb-8d85-545214e2f83a.jpg">

2020-11-23 08:26 UTC, chrisli30 approved these changes

2020-11-23 08:27 UTC, imstar15 approved these changes

2020-11-23 09:22 UTC, merged