Group Dapp Browser's dapps by network (Mainnet && Testnet)
rsksmart/rwallet pull request #617
Opened 2020-11-20 03:19 UTC by AmazingBeerBelly

![image](https://user-images.githubusercontent.com/25864116/99753895-313e9700-2b22-11eb-83a4-eeae114a029a.png)

2020-11-20 03:46 UTC, chrisli30 commented on src/common/translations/en.json
> +      "testnet": "Testnet",
这个词已经定义过了，没在dapp里，但是跟之前定义的完全一样，用外面定义的吧

2020-11-20 03:46 UTC, chrisli30 commented on src/pages/dapp/index.js
> +              column.push(this.getDappItem({ item, row }, [{ marginRight: 20, marginTop: row ? 15 : 0 }]));
这个 row？指的是 row !== 0 ？如果是的话，显示的写出来吧

2020-11-20 05:52 UTC, chrisli30 approved these changes
Okay, looks good to me 👍

2020-11-23 04:27 UTC, imstar15 requested changes

2020-11-23 04:27 UTC, imstar15 commented on src/pages/dapp/index.js
> +          title="page.wallet.selectCurrency.mainnet"
这个翻译，我已经抽出来了，现在应该使用'networkType.mainnet'和'networkType.testnet'
更新develop分支，合并到这个分支里，修改一下。

2020-11-23 04:27 UTC, imstar15 commented on src/pages/dapp/index.js
> +          title="page.wallet.selectCurrency.testnet"
同上

2020-11-23 07:00 UTC, imstar15 approved these changes

2020-11-23 07:01 UTC, merged