Dapp browser add warning when android clock the back button. Fix #600
rsksmart/rwallet pull request #622
Opened 2020-11-23 11:42 UTC by AmazingBeerBelly

![1791606131729_ pic](https://user-images.githubusercontent.com/25864116/99958240-fc516f00-2dc3-11eb-81ee-8a16c4757f93.jpg)

2020-11-23 15:04 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "backMessage": "Você está deixando a calçada, você tem certeza de querer existir?"
```suggestion
      "backMessage": "Você tem certeza de que deseja sair do dapp?"
```

2020-11-23 15:04 UTC, bitcoinuser requested changes
Minor change Brazilian Portuguese.

2020-11-23 21:11 UTC, chrisli30 approved these changes
没问题，安卓物理返回键的问题在这里处理了吗？。

2020-11-24 03:49 UTC, imstar15 approved these changes

2020-11-24 03:51 UTC, AmazingBeerBelly commented
是的

2020-11-24 05:52 UTC, merged