Fix infinite positive value display issue in transaction modal
rsksmart/rwallet pull request #628
Opened 2020-11-26 06:59 UTC by AmazingBeerBelly

在isPositiveInfinity方法中，我用了2 ** 256 - 1来作为最大的一个number，不能用Number.POSITIVE_INFINITY来对比，因为Number.MAX_VALUE = 1.7976931348623157e+308，是2 ** 1024 - 1，远大于rskswap那边传过来的2 ** 256 - 1。

<Img width="300" src="https://user-images.githubusercontent.com/25864116/100317478-61d97180-2ff7-11eb-90f9-07b924d86dcd.jpg" />

<Img width="300" src="https://user-images.githubusercontent.com/25864116/100317771-d7454200-2ff7-11eb-9044-8c6edc7e5fb2.jpg" />

<Img width="300" src="https://user-images.githubusercontent.com/25864116/100317801-e1ffd700-2ff7-11eb-9db6-5f16b34d6a83.jpg" />

2020-11-26 09:16 UTC, imstar15 approved these changes

2020-11-26 13:55 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "backMessage": "Você está deixando a calçada, você tem certeza de querer existir?",
```suggestion
      "backMessage": "Você tem certeza de que deseja sair do dapp?",
```

2020-11-26 13:56 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "infinitePositiveNumber": "Número infinito positivo"
```suggestion
      "infinitePositiveNumber": "Número positivo infinito"
```

2020-11-26 13:56 UTC, bitcoinuser requested changes
Minor changes Portuguese Brazilian

2020-11-29 07:02 UTC, chrisli30 commented
> POSITIVE_INFINITY

对，好的

2020-11-29 07:02 UTC, chrisli30 approved these changes

2020-11-30 01:41 UTC, merged