Make DApps search bar message more precise
rsksmart/rwallet pull request #677
Opened 2021-05-12 21:52 UTC by martinmedina

Previous DApp search bar message was "Search or enter website url" which was not correct because that bar does not allow any search to be done and it only accepts DApps URLs. An example of a DApp URL is `manager.rns.rifos.org` when a user wants to interact with. the RNS manager

This PR changes the message for "Enter the DApp website URL"  which is more precise and improves UX.

2021-05-13 13:28 UTC, patogallaiovlabs approved these changes
LGTM

2021-05-13 14:15 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "search": "Insira o URL do DApp site",
```suggestion
      "search": "Insira a página URL do DApp",
```

2021-05-13 14:15 UTC, bitcoinuser requested changes
Minor change PT-BR

2021-05-14 20:44 UTC, patogallaiovlabs commented on src/common/translations/pt.json
> +      "search": "Insira o URL do DApp site",
Shouldn't this be as 'pt-BR'?

2021-05-17 18:25 UTC, merged