WIP: extract tx broadcast from component and add unit test
rsksmart/rwallet pull request #687
Opened 2021-05-18 20:05 UTC by lucachaco

Please dont commit yet, work in progress
Extract tx broadcast code from component and add unit test (pending)

## Motivation and Context
Decouple logic from components to make them easier to test

## How Has This Been Tested?
No yet, just sharing working in progress.

## Types of changes

- [ ] fix: bug fixes, e.g. fix Button color on DarkTheme.
- [ ] feat: new features, e.g. add Snackbar component.
- [ x] refactor: code refactor, e.g. new folder structure for components.
- [ ] docs: changes into documentation, e.g. add usage example for Button.
- [ ] test: adding or updating tests, eg unit, snapshot testing.
- [ ] chore: tooling changes, e.g. change circleci config.
- [ ] BREAKING CHANGE: for changes that break existing usage, e.g. change API of a component.

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)

* **Other information**:

* **SCREENSHOTS**:

2021-05-19 04:35 UTC, lucachaco commented
<img width="669" alt="Screen Shot 2021-05-18 at 22 34 47" src="https://user-images.githubusercontent.com/85146/118756974-4eca9000-b829-11eb-9836-ac513fd5a37c.png">

2021-05-20 17:21 UTC, patogallaiovlabs requested changes

2021-05-20 19:41 UTC, lucachaco commented on src/services/transactionServices.js
> +  if (isRequestSendAll) {
Yes, good point. As discussed we cant do it in a different ticket.

2021-05-20 23:53 UTC, lucachaco commented on __test__/transactionServices.test.js
> +        expect(builtTransaction.symbol).toBe(segwitRbtcSendAllInput.coin.symbol);
Added.

2021-05-20 23:54 UTC, lucachaco commented on src/pages/wallet/transfer.js
> +      // transaction = null;
Removed..

2021-05-21 14:15 UTC, patogallaiovlabs approved these changes

2021-06-08 13:51 UTC, merged