Changes PT-BR
rsksmart/rwallet pull request #709
Opened 2021-06-25 00:15 UTC by bitcoinuser

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] fix: bug fixes, e.g. fix Button color on DarkTheme.
- [ ] feat: new features, e.g. add Snackbar component.
- [ ] refactor: code refactor, e.g. new folder structure for components.
- [ ] docs: changes into documentation, e.g. add usage example for Button.
- [ ] test: adding or updating tests, eg unit, snapshot testing.
- [ ] chore: tooling changes, e.g. change circleci config.
- [ ] BREAKING CHANGE: for changes that break existing usage, e.g. change API of a component.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)

* **Other information**:

* **SCREENSHOTS**:

2021-06-25 18:02 UTC, patogallaiovlabs requested changes
I would not change "ativo" to "criptoativo", its pretty obvious that we are talking about crypto since its a wallet, and we would also need to change in the rest of the languages.
Apart from that, I think its a nice PR :)

2021-06-25 18:06 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "allAssets": "Todos os criptoativos",
```suggestion
        "allAssets": "Todos os ativos",
```

2021-06-25 18:06 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "noTransNote": "Não foram encontradas transações realizadas com este criptoativo.",
```suggestion
        "noTransNote": "Não foram encontradas transações realizadas com este ativo.",
```

2021-06-25 18:07 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "title": "Selecionar criptoativos da carteira"
```suggestion
        "title": "Selecionar ativos da carteira"
```

2021-06-25 18:07 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "title": "Selecionar criptoativo"
```suggestion
        "title": "Selecionar ativo"
```

2021-06-25 18:07 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "selectMainnetAsset": "Selecione uma carteira que tenha pelo menos um criptoativo na rede principal da RSK",
```suggestion
        "selectMainnetAsset": "Selecione uma carteira que tenha pelo menos um ativo na rede principal da RSK",
```

2021-06-25 18:07 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "selectTestnetAsset": "Selecione uma carteira que tenha pelo menos um criptoativo na rede de testes da RSK",
```suggestion
        "selectTestnetAsset": "Selecione uma carteira que tenha pelo menos um ativo na rede de testes da RSK",
```

2021-06-25 18:08 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "assets": "Criptoativos",
```suggestion
        "assets": "Ativos",
```

2021-06-25 18:08 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "asset": "Criptoativo",
```suggestion
        "asset": "Ativo",
```

2021-06-25 18:08 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "title": "Selecionar criptoativo",
```suggestion
        "title": "Selecionar ativo",
```

2021-06-25 18:08 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "noSwappableCoin": "Desculpe, você não tem nenhum criptoativo para trocar",
```suggestion
        "noSwappableCoin": "Desculpe, você não tem nenhum ativo para trocar",
```

2021-06-25 18:08 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "title": "Adicionar criptoativos personalizados",
```suggestion
        "title": "Adicionar ativos personalizados",
```

2021-06-25 18:09 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "address": "Endereço do contrato do criptoativo"
```suggestion
        "address": "Endereço do contrato do ativo"
```

2021-06-25 18:09 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "title": "Adicionar criptoativos personalizados",
```suggestion
        "title": "Adicionar ativos personalizados",
```

2021-06-25 18:09 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "question": "Você deseja adicionar este criptoativo?",
```suggestion
        "question": "Você deseja adicionar este ativo?",
```

2021-06-25 18:09 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "token": "Ciptoativo",
```suggestion
        "token": "Ativo",
```

2021-06-25 18:09 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "symbol": "Símbolo do criptoativo",
```suggestion
        "symbol": "Símbolo do ativo",
```

2021-06-25 18:10 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "title": "Adicionar criptoativo",
```suggestion
        "title": "Adicionar ativo",
```

2021-06-25 18:10 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "enabledAssets": "Criptoativos habilitados",
```suggestion
        "enabledAssets": "Ativos habilitados",
```

2021-06-25 18:10 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "addCustomToken": "Adicionar criptoativo personalizado",
```suggestion
        "addCustomToken": "Adicionar ativo personalizado",
```

2021-06-25 18:10 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "question": "Encontramos abaixo os seguintes criptoativos nesta carteira. Você deseja monitorar este endereço?",
```suggestion
        "question": "Encontramos abaixo os seguintes ativos nesta carteira. Você deseja monitorar este endereço?",
```

2021-06-25 18:10 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "rnsQuestion": "Encontramos abaixo o endereço da carteira e os seguintes criptoativos. Você deseja monitorar este endereço?",
```suggestion
        "rnsQuestion": "Encontramos abaixo o endereço da carteira e os seguintes ativos. Você deseja monitorar este endereço?",
```

2021-06-25 18:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +          "one": "1 Criptoativo",
```suggestion
          "one": "1 Ativo",
```

2021-06-25 18:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +          "other": "{{count}} Criptoativos"
```suggestion
          "other": "{{count}} Ativos"
```

2021-06-25 18:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +          "one": "Esta carteira contém 1 criptoativo",
```suggestion
          "one": "Esta carteira contém 1 ativo",
```

2021-06-25 18:11 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +          "other": "Esta carteira contém {{count}} criptoativos"
```suggestion
          "other": "Esta carteira contém {{count}} ativos"
```

2021-06-25 18:12 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "Assets": "Criptoativos",
```suggestion
        "Assets": "Ativos",
```

2021-06-25 18:12 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "title": "Gerenciamento de criptoativos ao seu alcance",
```suggestion
        "title": "Gerenciamento de ativos ao seu alcance",
```

2021-06-25 18:12 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +    "addAsset": "Adicionar criptoativo",
```suggestion
    "addAsset": "Adicionar ativo",
```

2021-06-25 18:12 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "body": "Carteiras somente leitura permitem que você monitore criptoativos na blockchain sem a necessidade de importar as chaves de gasto.\n\nAtualmente são permitidos endereços Bitcoin (SegWit
```suggestion
      "body": "Carteiras somente leitura permitem que você monitore ativos na blockchain sem a necessidade de importar as chaves de gasto.\n\nAtualmente são permitidos endereços Bitcoin (SegWit e Legacy), endereços Rootstock ou apelidos RNS."
```

2021-06-25 18:12 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +      "asset": "Criptoativo",
```suggestion
      "asset": "Ativo",
```

2021-06-25 18:18 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "noTransNote": "Não foram encontradas transações realizadas com este criptoativo.",
```suggestion
        "noTransNote": "Não foram encontradas transações realizadas com este ativo.",
```

2021-06-25 18:18 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "addAsset": "Adicionar criptoativo",
```suggestion
        "addAsset": "Adicionar ativo",
```

2021-06-25 18:18 UTC, bitcoinuser commented on src/common/translations/pt-BR.json
> +        "timeoutBody": "A RWallet não conseguiu estabelecer uma conexão WalletConnect com o dapp dentro do prazo estabelecido. Por favor, tente novamente. Se o problema persistir, exclua todos os dad
```suggestion
        "timeoutBody": "A RWallet não conseguiu estabelecer uma conexão WalletConnect com o dapp dentro do prazo estabelecido. Por favor, tente novamente. Se o problema persistir, exclua todos os dados de navegação (cookies, cache, etc) no navegador que você está usando para acessar o dapp",
```

2021-06-25 18:19 UTC, bitcoinuser commented
> I would not change "ativo" to "criptoativo", its pretty obvious that we are talking about crypto since its a wallet, and we would also need to change in the rest of the languages.
> Apart from that, I think its a nice PR :)

Done.

2021-06-28 13:21 UTC, patogallaiovlabs approved these changes
LGTM

2021-06-28 13:21 UTC, merged