fix: filter duplicated tokens by contract address, not by symbol
rsksmart/rwallet pull request #717
Opened 2021-07-13 22:48 UTC by lucachaco

![image](https://user-images.githubusercontent.com/85146/125534923-859701bc-21be-40ac-9bc4-8f196af918a8.png)

2021-07-15 01:35 UTC, ilanolkies requested changes
Hey! I am testing it in Testnet and is not working with this two tokens:
- 0x14B95Eff39E55C6AACd491b083c8efb5C7A2f3A7
- 0xc4376Db2ca9b75D6b32e1dB4340A6A2D60FB6f4A

I successfully added the first one, and wasn't able to add the second one.

<img width="365" alt="Screen Shot 2021-07-14 at 22 34 42" src="https://user-images.githubusercontent.com/36084092/125714122-574584f8-732a-478d-a5e4-ae3cd1113de3.png">

I get this log

<img width="529" alt="Screen Shot 2021-07-14 at 22 58 28" src="https://user-images.githubusercontent.com/36084092/125716044-9367c26c-a204-42de-9baa-dbd3826306c5.png">

2021-07-15 01:36 UTC, ilanolkies commented
I changed the base to `develop` :)

2021-07-16 14:56 UTC, lucachaco commented
This should be fixed with this PR: https://github.com/rootstock/rwallet-server/pull/82

2021-08-02 04:44 UTC, ilanolkies approved these changes

2021-08-02 04:44 UTC, merged